services:
  email-service:
    container_name: microservice-emails
    build: ./ms-emails
    restart: always
    volumes:
      - ../../ms-emails:/var/www/html
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=emails
    depends_on:
      - mariadb
    ports:
      - "127.0.0.3:80:80"